### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by CAD97** [CAD97/MinecraftCommand#1]
- [ ] commands
  - [ ] achievement.md
  - [ ] ban-ip.md
  - [ ] ban.md
  - [ ] blockdata.md
  - [ ] clear.md
  - [ ] clone.md
  - [ ] debug.md
  - [ ] defaultgamemode.md
  - [ ] deop.md
  - [ ] difficulty.md
  - [ ] effect.md
  - [ ] enchant.md
  - [ ] entitydata.md
  - [ ] execute.md
  - [ ] fill.md
  - [ ] gamemode.md
  - [ ] gamerule.md
  - [ ] give.md
  - [ ] help.md
  - [ ] kick.md
  - [ ] kill.md
  - [ ] list.md
  - [ ] me.md
  - [ ] op.md
  - [ ] pardon.md
  - [ ] particle.md
  - [ ] playsound.md
  - [ ] publish.md
  - [ ] replaceitem.md
  - [ ] save-all.md
  - [ ] save-off.md
  - [ ] save-on.md
  - [ ] say.md
  - [ ] scoreboard.md
  - [ ] seed.md
  - [ ] setblock.md
  - [ ] setidletimeout.md
  - [ ] setworldspawn.md
  - [ ] spawnpoint.md
  - [ ] spreadplayers.md
  - [ ] stats.md
  - [ ] stop.md
  - [ ] summon.md
  - [ ] tell.md
  - [ ] tellraw.md
  - [ ] testfor.md
  - [ ] testforblock.md
  - [ ] testforblocks.md
  - [ ] time.md
  - [ ] title.md
  - [ ] toggledownfall.md
  - [ ] tp.md
  - [ ] trigger.md
  - [ ] weather.md
  - [ ] whitelist.md
  - [ ] worldborder.md
  - [ ] xp.md
